pub const MACOS_TYPE: u16 = 100;
pub const WINDOWS_TYPE: u16 = 200;
pub const LINUX_TYPE: u16 = 300;
pub const WINDOWS_KEY_STR: &'static str = "windows";
pub const MACOS_KEY_STR: &'static str = "macos";
pub const LINUX_KEY_STR: &'static str = "linux";
pub const ERROR_COMMAND_OUTPUT_PANIC: &'static str = "Error";
pub const ERROR_CHECK_OS: &'static str = "Error when match os type";
pub const ERROR_CHECK_FOLDER_NOT_EXIST: &'static str = "Error folder not exist";